name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploying API
        uses: fifsky/ssh-action@master
        with:
          command: |
            sudo service update-api start
          host: ${{ secrets.HOST }}
          user: ubuntu
          key: ${{ secrets.PRIVATE_KEY}}
          args: "-tt -vvv"
